{% set version = "1.5" %}

package:
  name: apbs
  version: {{ version }}

source:
  path: ../../

build:
  number: 5

requirements:
  build:
    - cmake
    - libgcc
    - swig
    - python
    - readline
    - ncurses
    # - mpich
    - fetk
    - lapack
    - blas
    - openblas
    - libgfortran
    # - arpack
    - geoflow_c
    - tabipb
    - pbam
    # - msms
    # - openblas
  run:
    - libgcc
    - python
    - readline
    - ncurses
    # - mpich
    - fetk
    - lapack
    - blas
    - openblas
    - libgfortran
    # - arpack
    - geoflow_c
    - tabipb
    - pbam
    # - msms
    # - openblas

test:
  source_files:
    - examples
  requires:
    - msms
  commands:
    - "apbs --help | grep 'APBS -- Adaptive Poisson-Boltzmann Solver'"
    - "apbs --version | grep 'Version'"

about:
  home: http://www.poissonboltzmann.org/
  summary: Adaptive Poisson-Boltzmann Solver.
  license: BSD
